### ISSUE TITLE
Where is the anti-islanding algorithm in this inverter?

### ISSUE THREAD

**Issue by kuchow** [NREL/PyPSCAD#1]
Thank you so much for providing this code, very helpful. I hope NREL will add more codes like this one.
For example these two reports:
https://www.nrel.gov/docs/fy13osti/58189.pdf
https://www.nrel.gov/docs/fy07osti/41109.pdf It will be very helpful to have the PSCAD models!

I have a question about this great code, thanks to the author and NREL, where is the anti-islanding scheme in this model? Can you please share the active and passive anti-islanding schemes? Thank you very much!

**Comment by afhoke** [comment]
The models do not contain anti-islanding controls.  For the GFM model, this is appropriate because anti-islanding is contrary to the goals of grid-forming control.  For the GFL model, we did not include anti-islanding because in our application the inverter model is used to represent an aggregation of many individual inverters, and island detection is not a use case in our project.  However, feel free to add your own anti-islanding controls if you like!
